### ISSUE TITLE
process_data_wiki_imdb.py: error

### ISSUE THREAD

**Issue by bj32161** [wayen820/gender_age_estimation_mxnet#16]
Hi,
I did run command as below. Please advice.

python3 ./process_data_wiki_imdb.py --rootpath ./imdb_crop --outputpath ../../datasets/imdb

usage: process_data_wiki_imdb.py [-h] --rootpath ROOTPATH --outputpath
                                 OUTPUTPATH --ratio RATIO --minscore MINSCORE
                                 [--align ALIGN]
process_data_wiki_imdb.py: error: the following arguments are required: --ratio, --minscore

**Comment by xysong1201** [comment]
> Hi,
> I did run command as below. Please advice.
> 
> python3 ./process_data_wiki_imdb.py --rootpath ./imdb_crop --outputpath ../../datasets/imdb
> 
> usage: process_data_wiki_imdb.py [-h] --rootpath ROOTPATH --outputpath
> OUTPUTPATH --ratio RATIO --minscore MINSCORE
> [--align ALIGN]
> process_data_wiki_imdb.py: error: the following arguments are required: --ratio, --minscore

Hi, just add --ration 0.8 --minscore 1.0

**Comment by bj32161** [comment]
> > Hi,
> > I did run command as below. Please advice.
> > python3 ./process_data_wiki_imdb.py --rootpath ./imdb_crop --outputpath ../../datasets/imdb
> > usage: process_data_wiki_imdb.py [-h] --rootpath ROOTPATH --outputpath
> > OUTPUTPATH --ratio RATIO --minscore MINSCORE
> > [--align ALIGN]
> > process_data_wiki_imdb.py: error: the following arguments are required: --ratio, --minscore
> 
> Hi, just add --ration 0.8 --minscore 1.0

I found another error as below
$python ./process_data_wiki_imdb.py --rootpath ./imdb_crop --outputpath ../../datasets/imdb --ratio 0.8 --minscore 1.0
..
..
Traceback (most recent call last):
  File "./process_data_wiki_imdb.py", line 99, in <module>
    main()
  File "./process_data_wiki_imdb.py", line 63, in main
    full_path, dob, gender, photo_taken, face_score, second_face_score, age=get_meta(os.path.join(rootpath, '%s.mat' %metafile), metafile)
NameError: name 'metafile' is not defined

**Comment by DavidGlezGmz** [comment]
Uncomment line 14: metafile='imdb'  #imdb or wiki (process_data_wiki_imdb.py). If you are using IMDB, that's correct, in case of  WIKI: metafile='wiki'
