### ISSUE TITLE
the test_img.py does not work normal

### ISSUE THREAD

**Issue by boyang24** [wayen820/gender_age_estimation_mxnet#3]
hi thanks for the project,now i already train the model,and i want to test the video and the ./img/ images,by  the given model,the test.py wroks good,even i did not change anything in test_img.py.it has the problem like:
![image](https://user-images.githubusercontent.com/41313271/47341041-8fde8000-d6d2-11e8-9970-45c6c72d0761.png)
i changed the 
![image](https://user-images.githubusercontent.com/41313271/47341185-f9f72500-d6d2-11e8-96d6-0172827b91db.png)
it has this problem,by the way,i used the model_silm***.py to slim the parameter,the age and gender model used in the test.py works good,but in test_img.py.it did not
so i want to ask what is the reason of this
thanks

**Comment by Lucien7786** [comment]
test.py have used :
       align_t=align_tools()
       nimg,box=align_t.get_intput_cv(frame)
before
        nimg = nimg[:, :, ::-1]
        nimg= np.transpose(nimg,(2,0,1))
but 
test_img.py did not do it at all.
that is to say, test_img.py did not do face detection work before age,gender model forward.

**Comment by xyddj** [comment]
Hi, when I run the test_img.py
I fixed the "align_tools" issue, but I still got an error as follows:

I use mxnet 1.20 instead of 1.1, is that the reason?

Traceback (most recent call last):
  File "test_new.py", line 82, in <module>
    main()
  File "test_new.py", line 70, in main
    model.forward(db, is_train=False)
  File "/data1/incubator-mxnet_120/python/mxnet/module/module.py", line 608, in forward
    self.reshape(new_dshape, new_lshape)
  File "/data1/incubator-mxnet_120/python/mxnet/module/module.py", line 470, in reshape
    self._exec_group.reshape(self._data_shapes, self._label_shapes)
  File "/data1/incubator-mxnet_120/python/mxnet/module/executor_group.py", line 382, in reshape
    self.bind_exec(data_shapes, label_shapes, reshape=True)
  File "/data1/incubator-mxnet_120/python/mxnet/module/executor_group.py", line 358, in bind_exec
    allow_up_sizing=True, **dict(data_shapes_i + label_shapes_i))
  File "/data1/incubator-mxnet_120/python/mxnet/executor.py", line 430, in reshape
    "If this is intended, set partial_shaping=True to suppress this warning.")
AssertionError: Shape of unspecified array arg:fullyconnected0_weight changed. This can cause the new executor to not share parameters with the old one. Please check for error in network.If this is intended, set partial_shaping=True to suppress this warning.

**Comment by xyddj** [comment]
I know! Images needs to be resized to 64*64!

**Comment by Lucien7786** [comment]
by calling nimg,box=align_t.get_intput_cv(frame)
or get_input() function code under align folder, it will do the face detection and detected face area will be affine transformed (including resize,rotate,translation,shear,flip) to 64*64 size. Notice that, not the whole image resize to 64*64, but only the detected face roi area affine transform to 64*64.

**Comment by Lucien7786** [comment]
by calling nimg,box=align_t.get_intput_cv(frame)
or get_input() function code under align folder, it will do the face detection and detected face area will be affine transformed (including resize,rotate,translation,shear,flip) to 64*64 size. Notice that, not the whole image resize to 64*64, but only the detected face roi area affine transform to 64*64.

**Comment by Lucien7786** [comment]
by calling nimg,box=align_t.get_intput_cv(frame)
or get_input() function code under align folder, it will do the face detection and detected face area will be affine transformed (including resize,rotate,translation,shear,flip) to 64*64 size. Notice that, not the whole image resize to 64*64, but only the detected face roi area affine transform to 64*64.

**Comment by Lucien7786** [comment]
by calling nimg,box=align_t.get_intput_cv(frame)
or get_input() function code under align folder, it will do the face detection and detected face area will be affine transformed (including resize,rotate,translation,shear,flip) to 64*64 size. Notice that, not the whole image resize to 64*64, but only the detected face roi area affine transform to 64*64.

**Comment by jake221** [comment]
> I know! Images needs to be resized to 64*64!

How to resize the image size to 64*64, can you post your code? Thanks!
