### ISSUE TITLE
test_img.py got mxnet AssertionError

### ISSUE THREAD

**Issue by xyddj** [wayen820/gender_age_estimation_mxnet#8]
I changed test.py for test images:

    path_image = './img_wide'
    for jpg in os.listdir(path_image):
        path_jpg = os.path.join(path_image, jpg)
        nimg = cv2.imread(path_jpg)

But I got an error like that, what's wrong?

Traceback (most recent call last):
  File "test_new.py", line 82, in <module>
    main()
  File "test_new.py", line 70, in main
    model.forward(db, is_train=False)
  File "/data1/incubator-mxnet_120/python/mxnet/module/module.py", line 608, in forward
    self.reshape(new_dshape, new_lshape)
  File "/data1/incubator-mxnet_120/python/mxnet/module/module.py", line 470, in reshape
    self._exec_group.reshape(self._data_shapes, self._label_shapes)
  File "/data1/incubator-mxnet_120/python/mxnet/module/executor_group.py", line 382, in reshape
    self.bind_exec(data_shapes, label_shapes, reshape=True)
  File "/data1/incubator-mxnet_120/python/mxnet/module/executor_group.py", line 358, in bind_exec
    allow_up_sizing=True, **dict(data_shapes_i + label_shapes_i))
  File "/data1/incubator-mxnet_120/python/mxnet/executor.py", line 430, in reshape
    "If this is intended, set partial_shaping=True to suppress this warning.")
AssertionError: Shape of unspecified array arg:fullyconnected0_weight changed. This can cause the new executor to not share parameters with the old one. Please check for error in network.If this is intended, set partial_shaping=True to suppress this warning.

**Comment by xyddj** [comment]
I added align part, it works...

        nimg,box=align_t.get_intput_cv(img)
        if nimg is None:
            continue
        nimg = nimg[:, :, ::-1]
        nimg= np.transpose(nimg,(2,0,1))

**Comment by xyddj** [comment]
I know! Images needs to be resized to 64*64!
